import { CellStatusEnum } from '@/types/enums';

export const FIELDS = [
  [
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
  ],
  [
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
  ],
  [
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
  ],
  [
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
  ],
  [
    CellStatusEnum.Empty,
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
  ],
  [
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
    CellStatusEnum.AliveShip,
  ],
];
